# Generated by Django 5.2.12 on 2026-05-17 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_alter_contact_import_batch'),
        ('crm', '0016_alter_pipeline_custom_fields_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_for', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='payments/invoices/')),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Card', 'Card'), ('Net Banking', 'Net Banking'), ('Other', 'Other')], default='UPI', max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contacts.contact')),
                ('crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.crm')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
