# Generated by Django 5.2.12 on 2026-05-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
