# Generated by Django 5.2.12 on 2026-07-31 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_crm_options'),
        ('payments', '0003_payment_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='crm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.crm'),
        ),
    ]
