# Generated by Django 5.2.12 on 2026-08-24 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contactlog_crm_set_null'),
        ('crm', '0020_add_assigned_user_to_pipeline'),
        ('payments', '0004_alter_payment_crm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_for', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Card', 'Card'), ('Net Banking', 'Net Banking'), ('Other', 'Other')], default='UPI', max_length=50)),
                ('cycle_period_days', models.PositiveIntegerField(default=30, help_text='Days between cycles')),
                ('cycle_count', models.PositiveIntegerField(default=1, help_text='Total number of cycles')),
                ('completed_cycles', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules', to='crm.crm')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules', to='crm.pipeline')),
            ],
            options={
                'verbose_name': 'Recurring Payment Schedule',
                'verbose_name_plural': 'Recurring Payment Schedules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact', 'status'], name='payments_re_contact_3f5c0b_idx'), models.Index(fields=['next_due_date'], name='payments_re_next_du_3e8d29_idx')],
            },
        ),
    ]
