# Generated by Django 5.2.12 on 2026-08-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contactlog_crm_set_null'),
        ('crm', '0020_add_assigned_user_to_pipeline'),
        ('payments', '0005_recurringpaymentschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpaymentschedule',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='recurringpaymentschedule',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='crm.pipeline'),
        ),
    ]
