# Generated by Django 5.2.12 on 2026-08-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_recurringpaymentschedule_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpaymentschedule',
            name='due_date',
            field=models.DateField(blank=True, help_text='Optional due date for single payment', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Any', 'Any'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], default='UPI', max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringpaymentschedule',
            name='payment_method',
            field=models.CharField(choices=[('Any', 'Any'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Card', 'Card'), ('Net Banking', 'Net Banking')], default='UPI', max_length=50),
        ),
    ]
