# Generated by Django 5.2.12 on 2026-04-11 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="User-defined import name, e.g. 'Q1 Trade Show Leads'", max_length=255)),
                ('contact_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, help_text='Import batch name, denormalized for fast filtering', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='The import batch this contact belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.importbatch'),
        ),
    ]
