# Generated by Django 5.2.12 on 2026-04-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_importbatch_contact_source_contact_import_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='The import batch this contact belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.importbatch'),
        ),
    ]
