# Generated by Django 6.0.6 on 2026-06-16 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contactremark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('photo', 'Photo'), ('proof', 'Proof Document'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='contact_documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contacts.contact')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Document',
                'verbose_name_plural': 'Contact Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
