# Generated by Django 6.0.6 on 2026-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Customer', 'Customer'), ('Inactive', 'Inactive'), ('Retarget', 'Retarget')], default='Lead', max_length=50),
        ),
    ]
