# Generated by Django 5.2.12 on 2026-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Customer', 'Customer'), ('Inactive', 'Inactive'), ('Retarget', 'Retarget'), ('Imports', 'Imports')], default='Lead', max_length=50),
        ),
    ]
