# Generated by Django 5.2.12 on 2026-07-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='pipeline_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
