# Generated by Django 5.2.12 on 2026-07-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_add_pipeline_name_to_contactlog'),
        ('crm', '0018_pipeline_pipeline_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlog',
            name='crm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='crm.crm'),
        ),
    ]
