# Generated by Django 5.2.12 on 2026-08-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contactlog_crm_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Customer', 'Customer'), ('Inactive', 'Inactive'), ('Retarget', 'Retarget'), ('Imports', 'Imports'), ('Payment Pending', 'Payment Pending')], default='Lead', max_length=50),
        ),
    ]
