# Generated by Django 5.2.12 on 2026-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_travel_agency_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='state_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
