# Generated by Django 5.2.12 on 2026-04-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_state_code_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='state_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
