# Generated by Django 5.2.12 on 2026-07-22 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0008_alter_user_role"),
        ("menus", "0005_menu_unique_system_menu_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Short prefix for work item keys, e.g., 'SK' for Smart Klub → SK-142",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "enabled_issue_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of issue types enabled: ['TASK', 'BUG', 'STORY', 'EPIC', ...]",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="authentication.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["workspace__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("dev_scrum", "Dev — Scrum"),
                            ("dev_kanban", "Dev — Kanban"),
                            ("sales_deal", "Sales — Deal Pipeline"),
                            ("support_ticket", "Support — Ticket"),
                            ("ops_approval", "Ops — Approval"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-assign this workflow to new projects of matching scope",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="workflows",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True, help_text="e.g., 'PROJ-142'", max_length=20
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("EPIC", "Epic"),
                            ("STORY", "Story"),
                            ("TASK", "Task"),
                            ("BUG", "Bug"),
                            ("SUBTASK", "Sub-task"),
                            ("DEAL", "Deal"),
                            ("TICKET", "Ticket"),
                            ("REQUEST", "Request"),
                            ("APPROVAL", "Approval"),
                            ("MILESTONE", "Milestone"),
                        ],
                        default="TASK",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Backlog/board ordering position"
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("labels", models.JSONField(blank=True, default=list)),
                (
                    "linked_object_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "linked_object_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="project_management.workitem",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="project_management.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_work_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Item",
                "verbose_name_plural": "Work Items",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkItemActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("ITEM_CREATED", "Item Created"),
                            ("ITEM_UPDATED", "Item Updated"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("ASSIGNEE_CHANGED", "Assignee Changed"),
                            ("PRIORITY_CHANGED", "Priority Changed"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("ATTACHMENT_ADDED", "Attachment Added"),
                            ("LINK_ADDED", "Link Added"),
                            ("LINK_REMOVED", "Link Removed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Item Activity Log",
                "verbose_name_plural": "Work Item Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkItemComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_item_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="project_management.workitemcomment",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Item Comment",
                "verbose_name_plural": "Work Item Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkItemLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("blocks", "Blocks"),
                            ("blocked_by", "Blocked By"),
                            ("relates_to", "Relates To"),
                            ("duplicates", "Duplicates"),
                            ("duplicated_by", "Duplicated By"),
                            ("converted_from", "Converted From"),
                            ("converted_to", "Converted To"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="project_management.workitem",
                    ),
                ),
                (
                    "target_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Item Link",
                "verbose_name_plural": "Work Item Links",
            },
        ),
        migrations.CreateModel(
            name="WorkItemStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="CSS color name/hex for UI rendering",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "is_start",
                    models.BooleanField(
                        default=False, help_text="Initial status for new items"
                    ),
                ),
                (
                    "is_end",
                    models.BooleanField(
                        default=False, help_text="Final/completion status"
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="project_management.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Item Status",
                "verbose_name_plural": "Work Item Statuses",
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.AddField(
            model_name="workitem",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_items",
                to="project_management.workitemstatus",
            ),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon name", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspaces",
                        to="menus.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace",
                "verbose_name_plural": "Workspaces",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="project_management.workspace",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("EDITOR", "Editor"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="project_management.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
                "indexes": [
                    models.Index(
                        fields=["project", "role"],
                        name="project_man_project_1e99e9_idx",
                    ),
                    models.Index(
                        fields=["user"], name="project_man_user_id_81cbf0_idx"
                    ),
                ],
                "unique_together": {("project", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["slug"], name="project_man_slug_c61c09_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["scope"], name="project_man_scope_de0118_idx"),
        ),
        migrations.AddIndex(
            model_name="workitemactivitylog",
            index=models.Index(
                fields=["work_item", "created_at"],
                name="project_man_work_it_98373d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workitemactivitylog",
            index=models.Index(
                fields=["activity_type"], name="project_man_activit_f06ee6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitemcomment",
            index=models.Index(
                fields=["work_item", "created_at"],
                name="project_man_work_it_432779_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workitemlink",
            index=models.Index(
                fields=["source_item", "relation_type"],
                name="project_man_source__cfa1df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workitemlink",
            index=models.Index(
                fields=["target_item", "relation_type"],
                name="project_man_target__90ff15_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workitemlink",
            unique_together={("source_item", "target_item", "relation_type")},
        ),
        migrations.AddIndex(
            model_name="workitemstatus",
            index=models.Index(
                fields=["workflow", "order"], name="project_man_workflo_3ea452_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workitemstatus",
            unique_together={("workflow", "slug")},
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["project", "status"], name="project_man_project_7fbb90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["assignee", "status"], name="project_man_assigne_c46712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(fields=["key"], name="project_man_key_4f1817_idx"),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["issue_type"], name="project_man_issue_t_881053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["due_date"], name="project_man_due_dat_9cb475_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["project", "issue_type"], name="project_man_project_0dd38e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["slug"], name="project_man_slug_060077_idx"),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(
                fields=["organization"], name="project_man_organiz_b6b894_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "is_active"], name="project_man_workspa_a17d7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["key"], name="project_man_key_81509a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("workspace", "key")},
        ),
    ]
