# Generated by Django 5.2.12 on 2026-07-22 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SprintMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capacity_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        help_text="Available hours for this sprint",
                        max_digits=6,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprint Member",
                "verbose_name_plural": "Sprint Members",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="sprint_capacity_hours",
            field=models.IntegerField(
                default=40,
                help_text="Default capacity per team member per sprint (hours)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sprint_duration_days",
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name="workitem",
            name="actual_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workitem",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent Epic that this item belongs to (issue_type=EPIC)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_items",
                to="project_management.workitem",
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workitem",
            name="story_points",
            field=models.IntegerField(
                blank=True,
                help_text="Estimation in story points (Fibonacci scale)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                related_name="watched_work_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workitemactivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("ITEM_CREATED", "Item Created"),
                    ("ITEM_UPDATED", "Item Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("ASSIGNEE_CHANGED", "Assignee Changed"),
                    ("PRIORITY_CHANGED", "Priority Changed"),
                    ("COMMENT_ADDED", "Comment Added"),
                    ("ATTACHMENT_ADDED", "Attachment Added"),
                    ("LINK_ADDED", "Link Added"),
                    ("LINK_REMOVED", "Link Removed"),
                    ("SPRINT_STARTED", "Sprint Started"),
                    ("SPRINT_CLOSED", "Sprint Closed"),
                    ("SPRINT_UPDATED", "Sprint Updated"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "goal",
                    models.TextField(blank=True, help_text="Sprint goal statement"),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                (
                    "total_capacity_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total team capacity in hours for this sprint",
                        max_digits=8,
                    ),
                ),
                (
                    "total_committed_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total story points committed for this sprint",
                        max_digits=8,
                    ),
                ),
                (
                    "total_completed_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total story points completed at sprint end",
                        max_digits=8,
                    ),
                ),
                ("retrospective_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="workitem",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_items",
                to="project_management.sprint",
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["sprint"], name="project_man_sprint__e63da3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(fields=["epic"], name="project_man_epic_id_9005f7_idx"),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["project", "story_points"],
                name="project_man_project_35b8fd_idx",
            ),
        ),
        migrations.AddField(
            model_name="sprintmember",
            name="sprint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="project_management.sprint",
            ),
        ),
        migrations.AddField(
            model_name="sprintmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sprint_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["project", "status"], name="project_man_project_a7571b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["project", "start_date"], name="project_man_project_877129_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sprintmember",
            unique_together={("sprint", "user")},
        ),
    ]
