# Generated by Django 5.2.12 on 2026-07-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_management",
            "0002_sprintmember_project_sprint_capacity_hours_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workitemactivitylog",
            name="work_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="project_management.workitem",
            ),
        ),
    ]
