# Generated by Django 5.2.12 on 2026-07-22 10:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0003_alter_workitemactivitylog_work_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="first_response_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of first agent response", null=True
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="requester_email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the customer who submitted the ticket",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="requester_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the customer who submitted the ticket",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="sla_resolution_due_at",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for resolution", null=True
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="sla_response_due_at",
            field=models.DateTimeField(
                blank=True, help_text="Deadline for first response", null=True
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="sla_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WITHIN_SLA", "Within SLA"),
                    ("WARNING", "Warning — approaching breach"),
                    ("BREACHED", "Breached"),
                    ("PAUSED", "Paused — waiting on customer"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workitemactivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("ITEM_CREATED", "Item Created"),
                    ("ITEM_UPDATED", "Item Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("ASSIGNEE_CHANGED", "Assignee Changed"),
                    ("PRIORITY_CHANGED", "Priority Changed"),
                    ("COMMENT_ADDED", "Comment Added"),
                    ("ATTACHMENT_ADDED", "Attachment Added"),
                    ("LINK_ADDED", "Link Added"),
                    ("LINK_REMOVED", "Link Removed"),
                    ("SPRINT_STARTED", "Sprint Started"),
                    ("SPRINT_CLOSED", "Sprint Closed"),
                    ("SPRINT_UPDATED", "Sprint Updated"),
                    ("SLA_BREACHED", "SLA Breached"),
                    ("SLA_WARNING", "SLA Warning"),
                    ("SLA_RESET", "SLA Reset"),
                    ("TICKET_ASSIGNED", "Ticket Assigned"),
                    ("CUSTOMER_RESPONDED", "Customer Responded"),
                    ("CSAT_SUBMITTED", "CSAT Submitted"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CSATResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 — Very Dissatisfied"),
                            (2, "2 — Dissatisfied"),
                            (3, "3 — Neutral"),
                            (4, "4 — Satisfied"),
                            (5, "5 — Very Satisfied"),
                        ]
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional customer feedback"
                    ),
                ),
                (
                    "responded_by",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the customer who submitted the response",
                        max_length=254,
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="csat_responses",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "CSAT Response",
                "verbose_name_plural": "CSAT Responses",
                "ordering": ["-responded_at"],
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        help_text="Which priority this SLA applies to",
                        max_length=20,
                    ),
                ),
                (
                    "response_time_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Target first response time in minutes"
                    ),
                ),
                (
                    "resolution_time_minutes",
                    models.PositiveIntegerField(
                        default=1440,
                        help_text="Target resolution time in minutes (default 24h)",
                    ),
                ),
                (
                    "business_hours_only",
                    models.BooleanField(
                        default=True, help_text="Only count time during business hours"
                    ),
                ),
                (
                    "business_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Business hours config: { 'timezone': 'Asia/Kolkata', 'days': {'mon': ['09:00','18:00'], ...} }",
                    ),
                ),
                (
                    "escalation_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of escalation rules: [{ 'after_minutes': 120, 'notify_role': 'Manager', 'action': 'reassign' }]",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_policies",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Policy",
                "verbose_name_plural": "SLA Policies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="workitem",
            name="sla_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_items",
                to="project_management.slapolicy",
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["sla_status"], name="project_man_sla_sta_402089_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["sla_response_due_at"], name="project_man_sla_res_aef983_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["sla_resolution_due_at"], name="project_man_sla_res_16a002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["requester_email"], name="project_man_request_3f9069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="csatresponse",
            index=models.Index(
                fields=["work_item"], name="project_man_work_it_56b026_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="csatresponse",
            index=models.Index(fields=["rating"], name="project_man_rating_423bba_idx"),
        ),
    ]
