# Generated by Django 5.2.12 on 2026-07-22 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0004_phase_2_5_ticketing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workitemactivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("ITEM_CREATED", "Item Created"),
                    ("ITEM_UPDATED", "Item Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("ASSIGNEE_CHANGED", "Assignee Changed"),
                    ("PRIORITY_CHANGED", "Priority Changed"),
                    ("COMMENT_ADDED", "Comment Added"),
                    ("ATTACHMENT_ADDED", "Attachment Added"),
                    ("LINK_ADDED", "Link Added"),
                    ("LINK_REMOVED", "Link Removed"),
                    ("SPRINT_STARTED", "Sprint Started"),
                    ("SPRINT_CLOSED", "Sprint Closed"),
                    ("SPRINT_UPDATED", "Sprint Updated"),
                    ("SLA_BREACHED", "SLA Breached"),
                    ("SLA_WARNING", "SLA Warning"),
                    ("SLA_RESET", "SLA Reset"),
                    ("TICKET_ASSIGNED", "Ticket Assigned"),
                    ("CUSTOMER_RESPONDED", "Customer Responded"),
                    ("CSAT_SUBMITTED", "CSAT Submitted"),
                    ("MILESTONE_ACHIEVED", "Milestone Achieved"),
                    ("MILESTONE_MISSED", "Milestone Missed"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("PROJECT", "Project Milestone"),
                            ("SPRINT", "Sprint Milestone"),
                            ("WORK_ITEM", "Work Item Milestone"),
                            ("GENERIC", "Generic Milestone"),
                        ],
                        default="GENERIC",
                        max_length=20,
                    ),
                ),
                ("target_date", models.DateTimeField()),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACHIEVED", "Achieved"),
                            ("MISSED", "Missed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "weight_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weight/importance percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "revenue_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="project_management.project",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones",
                        to="project_management.sprint",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone",
                "verbose_name_plural": "Milestones",
                "ordering": ["target_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="project_man_project_226325_idx",
                    ),
                    models.Index(
                        fields=["sprint"], name="project_man_sprint__7a15f9_idx"
                    ),
                    models.Index(
                        fields=["work_item"], name="project_man_work_it_3b7c5e_idx"
                    ),
                    models.Index(
                        fields=["target_date"], name="project_man_target__6c4351_idx"
                    ),
                    models.Index(
                        fields=["status"], name="project_man_status_504e65_idx"
                    ),
                ],
            },
        ),
    ]
