# Generated by Django 5.2.12 on 2026-07-22 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0005_phase_3_milestones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["project", "sprint"], name="project_man_project_9cda47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["project", "-created_at"], name="project_man_project_859c86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workitem",
            index=models.Index(
                fields=["project", "issue_type", "sla_status"],
                name="project_man_project_8c86f6_idx",
            ),
        ),
    ]
