# Generated by Django 5.2.12 on 2026-07-22 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0006_phase_4_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company"),
                            ("DEPARTMENT", "Department"),
                            ("TEAM", "Team"),
                            ("INDIVIDUAL", "Individual"),
                        ],
                        default="TEAM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ACHIEVED", "Achieved"),
                            ("MISSED", "Missed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "weight",
                    models.IntegerField(default=100, help_text="Relative weight 0-100"),
                ),
                (
                    "milestones",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Milestones that indicate progress",
                        related_name="objectives",
                        to="project_management.milestone",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_objectives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_objective",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent objective for tree hierarchy (e.g., Company → Department → Team)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_objectives",
                        to="project_management.objective",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectives",
                        to="project_management.project",
                    ),
                ),
                (
                    "work_items",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Work items that contribute to this objective",
                        related_name="objectives",
                        to="project_management.workitem",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="project_management.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeyResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "kr_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage (%)"),
                            ("NUMBER", "Number"),
                            ("CURRENCY", "Currency ($)"),
                            ("BOOLEAN", "Yes/No"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                ("start_value", models.FloatField(default=0)),
                ("target_value", models.FloatField(default=100)),
                ("current_value", models.FloatField(default=0)),
                ("progress_pct", models.FloatField(default=0, editable=False)),
                (
                    "metric_work_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional WorkItem (e.g. a Bug count query) that drives this KR",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="key_results",
                        to="project_management.workitem",
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_results",
                        to="project_management.objective",
                    ),
                ),
            ],
            options={
                "ordering": ["objective__title", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="objective",
            index=models.Index(
                fields=["workspace", "status"], name="project_man_workspa_e3dfbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objective",
            index=models.Index(fields=["owner"], name="project_man_owner_i_cbf218_idx"),
        ),
        migrations.AddIndex(
            model_name="objective",
            index=models.Index(
                fields=["alignment"], name="project_man_alignme_4258ef_idx"
            ),
        ),
    ]
