# Generated by Django 5.2.12 on 2026-07-22 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0007_phase_3_2_okr_goal_tree"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("ITEM_CREATED", "Work Item Created"),
                            ("ITEM_UPDATED", "Work Item Updated"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("ASSIGNEE_CHANGED", "Assignee Changed"),
                            ("PRIORITY_CHANGED", "Priority Changed"),
                            ("SPRINT_STARTED", "Sprint Started"),
                            ("SPRINT_ENDED", "Sprint Ended"),
                            ("SLA_BREACHED", "SLA Breached"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("DUE_DATE_APPROACHING", "Due Date Approaching"),
                        ],
                        max_length=30,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=list)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ASSIGN_TO", "Assign To"),
                            ("SET_STATUS", "Set Status"),
                            ("SET_PRIORITY", "Set Priority"),
                            ("ADD_LABEL", "Add Label"),
                            ("NOTIFY", "Send Notification"),
                            ("WEBHOOK", "Call Webhook"),
                            ("CREATE_SUBTASK", "Create Subtask"),
                            ("START_SLA", "Start SLA Timer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Action parameters: e.g. {'user_id': '...', 'status_id': '...', 'webhook_url': '...'}",
                    ),
                ),
                (
                    "issue_type_filter",
                    models.CharField(
                        blank=True,
                        help_text="If set, only applies to this issue type",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Execution priority (lower runs first)"
                    ),
                ),
                ("run_count", models.IntegerField(default=0, editable=False)),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["project", "trigger_event"],
                        name="project_man_project_ba608b_idx",
                    ),
                    models.Index(
                        fields=["is_enabled"], name="project_man_is_enab_a0e1e9_idx"
                    ),
                ],
            },
        ),
    ]
