# Generated by Django 5.2.12 on 2026-07-22 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0008_phase_3_4_automation_rule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ITEM_ASSIGNED", "Work Item Assigned"),
                            ("ITEM_UPDATED", "Work Item Updated"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("SLA_BREACHED", "SLA Breached"),
                            ("SLA_WARNING", "SLA Warning"),
                            ("MENTION", "You were mentioned"),
                            ("DUE_SOON", "Due Date Approaching"),
                            ("OVERDUE", "Item Overdue"),
                            ("SPRINT_STARTED", "Sprint Started"),
                            ("SPRINT_ENDED", "Sprint Ended"),
                            ("MILESTONE_ACHIEVED", "Milestone Achieved"),
                            ("SYSTEM", "System Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="project_management.project",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="project_man_recipie_8dea88_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="project_man_notific_3f6a74_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="project_man_created_dbe06e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ITEM_ASSIGNED", "Work Item Assigned"),
                            ("ITEM_UPDATED", "Work Item Updated"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("SLA_BREACHED", "SLA Breached"),
                            ("SLA_WARNING", "SLA Warning"),
                            ("MENTION", "You were mentioned"),
                            ("DUE_SOON", "Due Date Approaching"),
                            ("OVERDUE", "Item Overdue"),
                            ("SPRINT_STARTED", "Sprint Started"),
                            ("SPRINT_ENDED", "Sprint Ended"),
                            ("MILESTONE_ACHIEVED", "Milestone Achieved"),
                            ("SYSTEM", "System Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("SLACK", "Slack"),
                        ],
                        default="IN_APP",
                        max_length=10,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="project_management.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("user", "project", "notification_type", "channel")
                },
            },
        ),
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("SLACK", "Slack"),
                            ("DISCORD", "Discord"),
                            ("CUSTOM", "Custom Webhook"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("webhook_url", models.URLField(max_length=500)),
                (
                    "secret",
                    models.CharField(
                        blank=True, help_text="Optional signing secret", max_length=255
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of NotificationType values to forward",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("failure_count", models.IntegerField(default=0, editable=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_configs",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "provider"],
                        name="project_man_project_019bdb_idx",
                    ),
                    models.Index(
                        fields=["is_enabled"], name="project_man_is_enab_40f2fb_idx"
                    ),
                ],
            },
        ),
    ]
