# Generated by Django 5.2.12 on 2026-07-22 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0009_phase_3_5_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue_type_filter",
                    models.CharField(
                        blank=True,
                        help_text="If set, only applies to this issue type",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "field_key",
                    models.SlugField(
                        help_text="Key used in the JSON custom_fields object (e.g. 'deal_value')",
                        max_length=100,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("SELECT", "Select (Dropdown)"),
                            ("MULTI_SELECT", "Multi-Select"),
                            ("BOOLEAN", "Yes/No"),
                            ("URL", "URL"),
                            ("USER", "User"),
                        ],
                        default="TEXT",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available options for SELECT/MULTI_SELECT types",
                    ),
                ),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_defs",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "label"],
                "indexes": [
                    models.Index(
                        fields=["project", "is_active"],
                        name="project_man_project_921a69_idx",
                    ),
                    models.Index(
                        fields=["field_key"], name="project_man_field_k_a615fd_idx"
                    ),
                ],
                "unique_together": {("project", "field_key", "issue_type_filter")},
            },
        ),
    ]
