# Generated by Django 5.2.12 on 2026-07-22 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0010_phase_3_6_custom_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workitemactivitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("ITEM_CREATED", "Item Created"),
                    ("ITEM_UPDATED", "Item Updated"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("ASSIGNEE_CHANGED", "Assignee Changed"),
                    ("PRIORITY_CHANGED", "Priority Changed"),
                    ("COMMENT_ADDED", "Comment Added"),
                    ("ATTACHMENT_ADDED", "Attachment Added"),
                    ("LINK_ADDED", "Link Added"),
                    ("LINK_REMOVED", "Link Removed"),
                    ("SPRINT_STARTED", "Sprint Started"),
                    ("SPRINT_CLOSED", "Sprint Closed"),
                    ("SPRINT_UPDATED", "Sprint Updated"),
                    ("SLA_BREACHED", "SLA Breached"),
                    ("SLA_WARNING", "SLA Warning"),
                    ("SLA_RESET", "SLA Reset"),
                    ("TICKET_ASSIGNED", "Ticket Assigned"),
                    ("CUSTOMER_RESPONDED", "Customer Responded"),
                    ("CSAT_SUBMITTED", "CSAT Submitted"),
                    ("MILESTONE_ACHIEVED", "Milestone Achieved"),
                    ("MILESTONE_MISSED", "Milestone Missed"),
                    ("SPRINT_CHANGED", "Sprint Changed"),
                    ("TITLE_CHANGED", "Title Changed"),
                    ("DESCRIPTION_CHANGED", "Description Changed"),
                    ("DUE_DATE_CHANGED", "Due Date Changed"),
                    ("STORY_POINTS_CHANGED", "Story Points Changed"),
                    ("FIELD_UPDATED", "Field Updated"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProjectFieldVisibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("VIEWER", "Viewer"),
                            ("MEMBER", "Member"),
                            ("EDITOR", "Editor"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "visible_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field names that this role can see. Empty = all fields.",
                    ),
                ),
                (
                    "hidden_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field names explicitly hidden from this role.",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_visibility_rules",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "role")},
            },
        ),
    ]
