# Generated by Django 5.2.12 on 2026-07-23 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0011_phase_4_3_4_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="parent_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent project for hierarchy (e.g., Programme → Project → Initiative)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_projects",
                to="project_management.project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sync_department_members",
            field=models.BooleanField(
                default=False,
                help_text="Auto-sync members from the linked HR department",
            ),
        ),
    ]
