# Generated by Django 5.2.12 on 2026-07-24 05:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0012_phase_project_hierarchy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="epic_priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CRITICAL", "Critical"),
                    ("HIGH", "High"),
                    ("MEDIUM", "Medium"),
                    ("LOW", "Low"),
                    ("NONE", "None"),
                ],
                default="NONE",
                help_text="Priority within epic hierarchy (only meaningful for EPIC issue_type)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Semantic version string, e.g., '1.2.3'",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RELEASED", "Released"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release",
                "verbose_name_plural": "Releases",
                "ordering": ["-release_date", "name"],
            },
        ),
        migrations.AddField(
            model_name="workitem",
            name="version",
            field=models.ForeignKey(
                blank=True,
                help_text="Release/version that this item is tagged to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_items",
                to="project_management.release",
            ),
        ),
        migrations.CreateModel(
            name="WorkItemAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="work_attachments/%Y/%m/"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Item Attachment",
                "verbose_name_plural": "Work Item Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["project", "status"], name="project_man_project_aad0e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["project", "is_archived"], name="project_man_project_2694d7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="release",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="workitemattachment",
            index=models.Index(
                fields=["work_item", "created_at"],
                name="project_man_work_it_a779aa_idx",
            ),
        ),
    ]
