# Generated by Django 5.2.12 on 2026-07-24 05:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_management",
            "0013_workitem_epic_priority_release_workitem_version_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("workflow_preset", models.CharField(blank=True, max_length=50)),
                ("default_issue_types", models.JSONField(blank=True, default=list)),
                (
                    "template_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Predefined work items, milestones, sprints configuration",
                    ),
                ),
                ("is_global", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="workitem",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workitem",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workitem",
            name="recurrence_rule",
            field=models.CharField(
                blank=True,
                help_text="RRULE string or frequency label: DAILY|WEEKLY|MONTHLY|etc",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_order", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                (
                    "assignee_role",
                    models.CharField(
                        blank=True, help_text="Role required to approve", max_length=50
                    ),
                ),
                (
                    "required_approvals",
                    models.IntegerField(
                        default=1, help_text="For parallel: how many must approve"
                    ),
                ),
                (
                    "assignee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="project_management.workitem",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_requests",
                        to="project_management.approvalstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("APPROVE", "Approve"), ("REJECT", "Reject")],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="project_management.approvalrequest",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="project_management.approvalstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "issue_type_filter",
                    models.CharField(
                        blank=True,
                        help_text="Apply to specific issue type, or leave blank for all",
                        max_length=50,
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Step"),
                            ("SEQUENTIAL", "Sequential"),
                            ("PARALLEL", "Parallel"),
                            ("ANY", "Any Approver"),
                        ],
                        default="SEQUENTIAL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_workflows",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="project_management.approvalworkflow",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="project_management.approvalworkflow",
            ),
        ),
        migrations.CreateModel(
            name="CannedResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Available across all projects"
                    ),
                ),
                (
                    "shortcut",
                    models.CharField(
                        blank=True,
                        help_text="Keyboard shortcut eg. /thankyou",
                        max_length=50,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_responses",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="GitHubIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repo_owner", models.CharField(max_length=255)),
                ("repo_name", models.CharField(max_length=255)),
                ("repo_full_name", models.CharField(blank=True, max_length=512)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_transition",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-transition work items when PR is merged",
                    ),
                ),
                (
                    "branch_prefix",
                    models.CharField(
                        blank=True, help_text="e.g. feature/, bugfix/", max_length=100
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_integration",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("repo_owner", "repo_name")},
            },
        ),
        migrations.CreateModel(
            name="GitHubLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("PR", "Pull Request"),
                            ("COMMIT", "Commit"),
                            ("ISSUE", "Issue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("github_id", models.BigIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("url", models.URLField(blank=True, max_length=1024)),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="e.g. open, closed, merged", max_length=50
                    ),
                ),
                ("branch", models.CharField(blank=True, max_length=255)),
                ("event_data", models.JSONField(blank=True, default=dict)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="project_management.githubintegration",
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_links",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriorityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="List of keywords/patterns to match"
                    ),
                ),
                (
                    "suggested_priority",
                    models.CharField(
                        choices=[
                            ("LOWEST", "Lowest"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("HIGHEST", "Highest"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_rules",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "ordering": ["suggested_priority"],
            },
        ),
        migrations.CreateModel(
            name="RecurringTaskConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Bi-Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(default=1, help_text="Every N frequency units"),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True, default=list, help_text="For weekly: [0=Mon, 6=Sun]"
                    ),
                ),
                ("day_of_month", models.IntegerField(blank=True, null=True)),
                ("month_of_year", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("max_occurrences", models.IntegerField(blank=True, null=True)),
                ("next_occurrence", models.DateField(blank=True, null=True)),
                (
                    "auto_create",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-create next occurrence when current is completed",
                    ),
                ),
                ("occurrences_created", models.IntegerField(default=0)),
                (
                    "work_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_config",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="approvalstep",
            unique_together={("workflow", "step_order")},
        ),
    ]
