# Generated by Django 5.2.12 on 2026-07-24 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0014_projecttemplate_workitem_is_recurring_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItemTimeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="project_management.workitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Item Time Log",
                "verbose_name_plural": "Work Item Time Logs",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
