# Generated by Django 5.2.12 on 2026-07-24 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0015_workitemtimelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=1024)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("request_body", models.JSONField(blank=True, default=dict)),
                ("response_body", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="project_management.webhookconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery Log",
                "verbose_name_plural": "Webhook Delivery Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
