# Generated by Django 5.2.12 on 2026-07-24 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0016_webhookdeliverylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "required_role",
                    models.CharField(
                        blank=True,
                        help_text="Role required to perform this transition",
                        max_length=50,
                    ),
                ),
                (
                    "required_field_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Field keys that must have values before transition",
                    ),
                ),
                (
                    "require_comment",
                    models.BooleanField(
                        default=False, help_text="Require a comment on transition"
                    ),
                ),
                (
                    "require_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Require an approval request before allowing transition",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        help_text="Custom error message shown when gate blocks transition",
                        max_length=255,
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_rules_from",
                        to="project_management.workitemstatus",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_rules_to",
                        to="project_management.workitemstatus",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_rules",
                        to="project_management.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "from_status", "to_status"],
                "unique_together": {("workflow", "from_status", "to_status")},
            },
        ),
    ]
