# Generated by Django 5.2.12 on 2026-07-24 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0017_transitionrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="digest_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Receive daily/weekly digest instead of real-time",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="digest_frequency",
            field=models.CharField(
                blank=True,
                choices=[("DAILY", "Daily"), ("WEEKLY", "Weekly")],
                default="DAILY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to="project_management.project",
            ),
        ),
    ]
