# Generated by Django 5.2.12 on 2026-07-24 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0018_notificationpreference_digest_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("workspace", "Workspace"),
                            ("project", "Project"),
                            ("my_work", "My Work"),
                        ],
                        default="project",
                        max_length=20,
                    ),
                ),
                (
                    "filter_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object of filter key-value pairs",
                    ),
                ),
                (
                    "column_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object for visible columns and their order",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Auto-apply this filter on page load"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to="project_management.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to="project_management.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Filter",
                "verbose_name_plural": "Saved Filters",
                "ordering": ["user", "name"],
                "unique_together": {("user", "name", "project")},
            },
        ),
    ]
