# Generated by Django 5.2.12 on 2026-07-24 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_management", "0019_savedfilter"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItemTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "issue_type",
                    models.CharField(
                        help_text="Work item type this template creates (TASK, BUG, STORY, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "template_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default field values: title, description, story_points, priority, etc.",
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Predefined checklist items: [{'text': '...', 'checked': false}, ...]",
                    ),
                ),
                ("is_global", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_item_templates",
                        to="project_management.project",
                    ),
                ),
                (
                    "project_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_item_templates",
                        to="project_management.projecttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
