# Generated by Django 6.0.6 on 2026-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0020_workitemtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='scope',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('project', 'Project'), ('my_work', 'My Work'), ('roadmap', 'Roadmap')], default='project', max_length=20),
        ),
    ]
