# Generated by Django 5.2.12 on 2026-05-22 18:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0007_remove_user_department_user_departments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppraisalCycle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Closed", "Closed")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appraisal Cycle",
                "verbose_name_plural": "Appraisal Cycles",
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/%Y/%m/"),
                ),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                (
                    "experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
            ],
            options={
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidates",
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("CASUAL", "Casual Leave"),
                            ("SICK", "Sick Leave"),
                            ("EARNED", "Earned Leave"),
                            ("MATERNITY", "Maternity Leave"),
                            ("PATERNITY", "Paternity Leave"),
                            ("BEREAVEMENT", "Bereavement Leave"),
                            ("COMP_OFF", "Compensatory Off"),
                            ("OPTIONAL", "Optional Holiday"),
                            ("LWP", "Leave Without Pay"),
                            ("MARRIAGE", "Marriage Leave"),
                            ("STUDY", "Study Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("default_annual_allocation", models.IntegerField(default=0)),
                (
                    "accrual_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="ANNUAL",
                        max_length=20,
                    ),
                ),
                ("max_carry_forward", models.IntegerField(default=0)),
                ("can_go_negative", models.BooleanField(default=False)),
                ("min_balance_required", models.IntegerField(default=0)),
                ("max_continuous_days", models.IntegerField(default=999)),
                ("is_encashable", models.BooleanField(default=False)),
                ("encashment_max_days", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("EARNINGS", "Earnings"),
                            ("DEDUCTIONS", "Deductions"),
                            ("FIXED", "Fixed"),
                            ("VARIABLE", "Variable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_fixed", models.BooleanField(default=True)),
                ("depends_on_basic", models.BooleanField(default=False)),
                (
                    "percentage_of_basic",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_taxable", models.BooleanField(default=False)),
                ("is_statutory", models.BooleanField(default=False)),
                (
                    "exemption_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("gl_account", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Salary Component",
                "verbose_name_plural": "Salary Components",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General (9 AM - 6 PM)"),
                            ("ROTATIONAL", "Rotational"),
                            ("NIGHT", "Night Shift"),
                            ("FLEXIBLE", "Flexible"),
                            ("REMOTE", "Remote"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_duration_minutes", models.IntegerField(default=60)),
                ("is_rotating", models.BooleanField(default=False)),
                (
                    "rotation_pattern",
                    models.TextField(
                        blank=True, help_text="Days or weeks for rotation", null=True
                    ),
                ),
                (
                    "night_shift_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("Internal", "Internal"),
                            ("External", "External"),
                            ("Online", "Online"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "trainer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pin_code", models.CharField(blank=True, max_length=10)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Work Location",
                "verbose_name_plural": "Work Locations",
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Center",
                "verbose_name_plural": "Cost Centers",
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=20, null=True)),
                ("band", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Designation",
                "verbose_name_plural": "Designations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A_POSITIVE", "A+"),
                            ("A_NEGATIVE", "A-"),
                            ("B_POSITIVE", "B+"),
                            ("B_NEGATIVE", "B-"),
                            ("AB_POSITIVE", "AB+"),
                            ("AB_NEGATIVE", "AB-"),
                            ("O_POSITIVE", "O+"),
                            ("O_NEGATIVE", "O-"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("nationality", models.CharField(default="Indian", max_length=50)),
                ("personal_email", models.EmailField(max_length=254, unique=True)),
                (
                    "personal_mobile",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Invalid phone number"
                            )
                        ],
                    ),
                ),
                ("current_address", models.TextField()),
                ("current_city", models.CharField(max_length=50)),
                ("current_state", models.CharField(max_length=50)),
                ("current_country", models.CharField(default="India", max_length=50)),
                ("current_pin_code", models.CharField(max_length=10)),
                ("permanent_address", models.TextField()),
                ("permanent_city", models.CharField(max_length=50)),
                ("permanent_state", models.CharField(max_length=50)),
                ("permanent_country", models.CharField(default="India", max_length=50)),
                ("permanent_pin_code", models.CharField(max_length=10)),
                (
                    "emergency_contact_1_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_1_mobile",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_1_relation",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "emergency_contact_2_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_2_mobile",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_2_relation",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True,
                        help_text="12-digit Aadhaar number",
                        max_length=12,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{12}$", "Aadhaar must be 12 digits"
                            )
                        ],
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        help_text="PAN in format: ABCDE1234F",
                        max_length=10,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{5}[0-9]{4}[A-Z]{1}$", "Invalid PAN format"
                            )
                        ],
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "voter_id_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "driving_license_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ifsc_code",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{4}0[A-Z0-9]{6}$", "Invalid IFSC code"
                            )
                        ],
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "spouse_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "number_of_children",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dependents",
                    models.TextField(
                        blank=True, help_text="JSON or comma-separated list", null=True
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("CONTRACT", "Contract"),
                            ("TRAINEE", "Trainee"),
                            ("INTERN", "Intern"),
                            ("PART_TIME", "Part-Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                ("notice_period_days", models.IntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CANDIDATE", "Candidate"),
                            ("OFFERED", "Offered"),
                            ("ONBOARDING", "Onboarding"),
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("NOTICE_PERIOD", "Notice Period"),
                            ("SEPARATED", "Separated"),
                        ],
                        default="ONBOARDING",
                        max_length=20,
                    ),
                ),
                ("separation_date", models.DateField(blank=True, null=True)),
                (
                    "separation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESIGNED", "Resigned"),
                            ("TERMINATED", "Terminated"),
                            ("ABSCONDED", "Absconded"),
                            ("RETIRED", "Retired"),
                            ("DECEASED", "Deceased"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("separation_notes", models.TextField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=20, null=True)),
                ("band", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "company_entity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "work_shift",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General (9 AM - 6 PM)"),
                            ("ROTATIONAL", "Rotational"),
                            ("NIGHT", "Night Shift"),
                            ("FLEXIBLE", "Flexible"),
                            ("REMOTE", "Remote"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_photos/%Y/%m/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.costcenter",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="authentication.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.designation",
                    ),
                ),
                (
                    "dotted_reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dotted_subordinates",
                        to="hr.employee",
                    ),
                ),
                (
                    "reporting_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="hr.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="hr.worklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="CompensatoryOff",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earned_on_date", models.DateField()),
                ("earned_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("availed_on_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EARNED", "Earned"),
                            ("AVAILED", "Availed"),
                            ("LAPSED", "Lapsed"),
                        ],
                        default="EARNED",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comp_offs",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compensatory Off",
                "verbose_name_plural": "Compensatory Offs",
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("OFFER_LETTER", "Offer Letter"),
                            ("APPOINTMENT_LETTER", "Appointment Letter"),
                            ("10TH_CERTIFICATE", "10th Certificate"),
                            ("12TH_CERTIFICATE", "12th Certificate"),
                            ("UG_CERTIFICATE", "UG Certificate"),
                            ("PG_CERTIFICATE", "PG Certificate"),
                            ("PROFESSIONAL_CERT", "Professional Certificate"),
                            ("EXPERIENCE_CERT", "Experience Certificate"),
                            ("BGV_DOCUMENT", "BGV Document"),
                            ("AADHAAR", "Aadhaar"),
                            ("PAN", "PAN"),
                            ("PASSPORT", "Passport"),
                            ("VOTER_ID", "Voter ID"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("BANK_DETAILS", "Bank Details"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(upload_to="employee_documents/%Y/%m/"),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Document",
                "verbose_name_plural": "Employee Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobRequisition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vacancies", models.PositiveIntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Closed", "Closed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("justification", models.TextField()),
                (
                    "budget_allocated",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.designation"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitions_raised",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Requisition",
                "verbose_name_plural": "Job Requisitions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Screening", "Screening"),
                            ("L1_Interview", "L1 Interview"),
                            ("L2_Interview", "L2 Interview"),
                            ("HR_Round", "HR Round"),
                            ("Offered", "Offered"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Applied",
                        max_length=50,
                    ),
                ),
                ("applied_on", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="hr.candidate",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="hr.jobrequisition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("number_of_days", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.TextField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("approval_comment", models.TextField(blank=True, null=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("cancelled_date", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("is_backdated", models.BooleanField(default=False)),
                (
                    "approval_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_applications",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
                "ordering": ["-applied_date"],
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("payroll_period", models.CharField(max_length=20)),
                (
                    "working_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "present_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "absent_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("half_day_count", models.IntegerField(default=0)),
                (
                    "leave_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gross_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "arrears",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "final_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSED", "Processed"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("bank_transfer_date", models.DateField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_records",
                        to="hr.employee",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payrolls",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceGoal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("weightage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(default="Pending", max_length=20)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.appraisalcycle",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "self_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "manager_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "final_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("manager_comments", models.TextField(blank=True, null=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.appraisalcycle",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resignation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_on", models.DateField(auto_now_add=True)),
                ("reason", models.TextField()),
                ("requested_last_working_day", models.DateField()),
                ("approved_last_working_day", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Withdrawn", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resignations",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExitClearance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_cleared", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.department",
                    ),
                ),
                (
                    "resignation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.resignation"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("grade", models.CharField(blank=True, max_length=20, null=True)),
                ("band", models.CharField(blank=True, max_length=20, null=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.designation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Structure",
                "verbose_name_plural": "Salary Structures",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ctc", models.DecimalField(decimal_places=2, max_digits=15)),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=15)),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=15)),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=15)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_details",
                        to="hr.employee",
                    ),
                ),
                (
                    "previous_salary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_salary",
                        to="hr.employeesalary",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.salarystructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Salary",
                "verbose_name_plural": "Employee Salaries",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="TrainingNomination",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Nominated", "Nominated"),
                            ("Approved", "Approved"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "completion_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.employee"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.trainingprogram",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("holiday_date", models.DateField()),
                ("is_national", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "applicable_locations",
                    models.ManyToManyField(blank=True, to="hr.worklocation"),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["holiday_date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "check_in_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "check_out_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("HALF_DAY", "Half Day"),
                            ("WFH", "Work From Home"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        default="ABSENT",
                        max_length=20,
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("late_by_minutes", models.IntegerField(default=0)),
                ("is_early_checkout", models.BooleanField(default=False)),
                ("early_by_minutes", models.IntegerField(default=0)),
                ("is_regularized", models.BooleanField(default=False)),
                ("regularization_reason", models.TextField(blank=True, null=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General (9 AM - 6 PM)"),
                            ("ROTATIONAL", "Rotational"),
                            ("NIGHT", "Night Shift"),
                            ("FLEXIBLE", "Flexible"),
                            ("REMOTE", "Remote"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "regularized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="hr_attendan_employe_c63029_idx",
                    ),
                    models.Index(fields=["date"], name="hr_attendan_date_3a46d7_idx"),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeLeaveBalance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "accrued_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "used_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "pending_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "encashed_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "lapsed_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.leavetype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Leave Balance",
                "verbose_name_plural": "Employee Leave Balances",
                "unique_together": {("employee", "leave_type", "financial_year")},
            },
        ),
        migrations.CreateModel(
            name="PayrollComponentDetail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="hr.payroll",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.salarycomponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Component Detail",
                "verbose_name_plural": "Payroll Component Details",
                "unique_together": {("payroll", "component")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureDetail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_percentage", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.salarycomponent",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="hr.salarystructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Structure Detail",
                "verbose_name_plural": "Salary Structure Details",
                "ordering": ["order"],
                "unique_together": {("salary_structure", "component")},
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_id"], name="hr_employee_employe_ec40c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["aadhaar_number"], name="hr_employee_aadhaar_afe18e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["pan_number"], name="hr_employee_pan_num_2c2fd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["status"], name="hr_employee_status_75bd6c_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department"], name="hr_employee_departm_1b8ba9_idx"
            ),
        ),
    ]
