# Generated by Django 5.2.12 on 2026-07-10 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_bonusconfiguration_esiconfiguration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRegularizationRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_check_in", models.TimeField(blank=True, null=True)),
                ("requested_check_out", models.TimeField(blank=True, null=True)),
                (
                    "requested_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("HALF_DAY", "Half Day"),
                            ("WFH", "Work From Home"),
                            ("ON_LEAVE", "On Leave"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("approval_comment", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_regularizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regularization_requests",
                        to="hr.attendance",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regularization_requests",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Regularization Request",
                "verbose_name_plural": "Attendance Regularization Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LWFConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("HALF_YEARLY", "Half-Yearly"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="HALF_YEARLY",
                        help_text="Most states: June & December",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "LWF Configuration",
                "verbose_name_plural": "LWF Configurations",
                "ordering": ["state"],
                "unique_together": {("state", "effective_from")},
            },
        ),
        migrations.CreateModel(
            name="ShiftSwapRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requesting_shift_date",
                    models.DateField(
                        help_text="Date requesting employee wants to swap FROM"
                    ),
                ),
                (
                    "target_shift_date",
                    models.DateField(
                        help_text="Date requesting employee wants to swap TO"
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "target_employee_consented",
                    models.BooleanField(
                        blank=True,
                        help_text="None=Pending, True=Accepted, False=Declined",
                        null=True,
                    ),
                ),
                ("target_consent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONSENT", "Pending Target Employee Consent"),
                            ("PENDING_MANAGER", "Pending Manager Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING_CONSENT",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_shift_swaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_swap_requests_made",
                        to="hr.employee",
                    ),
                ),
                (
                    "requesting_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swap_requests_from",
                        to="hr.shift",
                    ),
                ),
                (
                    "target_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_swap_requests_received",
                        to="hr.employee",
                    ),
                ),
                (
                    "target_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swap_requests_to",
                        to="hr.shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Swap Request",
                "verbose_name_plural": "Shift Swap Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LWFContribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("JAN_JUN", "January–June"),
                            ("JUL_DEC", "July–December"),
                            ("ANNUAL", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year", models.IntegerField()),
                ("state", models.CharField(max_length=100)),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_challan_generated", models.BooleanField(default=False)),
                (
                    "challan_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.lwfconfiguration",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lwf_contributions",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lwf_contributions",
                        to="hr.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "LWF Contribution",
                "verbose_name_plural": "LWF Contributions",
                "ordering": ["-year", "state"],
                "unique_together": {("employee", "period", "year")},
            },
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "ot_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("reason", models.TextField()),
                (
                    "ot_rate_multiplier",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.5,
                        help_text="1.5 for regular OT, 2.0 for holiday/night OT (as per Factories Act)",
                        max_digits=3,
                    ),
                ),
                (
                    "ot_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PROCESSED", "Processed in Payroll"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("approval_comment", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_overtime_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_requests",
                        to="hr.attendance",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overtime_requests",
                        to="hr.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overtime Request",
                "verbose_name_plural": "Overtime Requests",
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
