# Generated by Django 5.2.12 on 2026-07-13 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0006_add_lwf_overtime_shift_swap_regularization"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="official_email",
            field=models.EmailField(
                blank=True,
                help_text="Company-provided email address",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="current_pin_code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "PIN code must be exactly 6 digits"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="permanent_pin_code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "PIN code must be exactly 6 digits"
                    )
                ],
            ),
        ),
    ]
