# Generated by Django 5.2.12 on 2026-07-13 08:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0007_add_official_email_pin_validation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ESICard",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_number",
                    models.CharField(
                        help_text="Insured Person Number", max_length=50, unique=True
                    ),
                ),
                (
                    "name_as_per_card",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "card_file",
                    models.FileField(
                        blank=True, null=True, upload_to="esi_cards/%Y/%m/"
                    ),
                ),
                ("dependents", models.JSONField(blank=True, default=list)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esi_cards",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "ESI Card",
                "verbose_name_plural": "ESI Cards",
            },
        ),
        migrations.CreateModel(
            name="Form12BA",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "perquisite_type",
                    models.CharField(
                        choices=[
                            ("RENT_FREE_ACCOMMODATION", "Rent-Free Accommodation"),
                            ("CONCESSIONAL_RENT", "Concessional Rent Accommodation"),
                            ("MOTOR_CAR", "Motor Car"),
                            ("SWEEPER_GARDENER", "Sweeper/Gardener/Servant"),
                            ("GAS_ELECTRICITY", "Gas/Electricity/Water"),
                            ("EDUCATION", "Children Education Allowance"),
                            ("TRANSPORT", "Transport Facility"),
                            ("SUNDRY", "Other Sundry Perquisites"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_12ba",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form 12BA - Perquisite",
                "verbose_name_plural": "Form 12BA - Perquisites",
                "ordering": ["-financial_year", "employee"],
            },
        ),
        migrations.CreateModel(
            name="Form24QReturn",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "Quarter 1 (Apr-Jun)"),
                            ("Q2", "Quarter 2 (Jul-Sep)"),
                            ("Q3", "Quarter 3 (Oct-Dec)"),
                            ("Q4", "Quarter 4 (Jan-Mar)"),
                        ],
                        max_length=5,
                    ),
                ),
                ("filing_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "token_number",
                    models.CharField(
                        blank=True, help_text="TRACES token", max_length=100, null=True
                    ),
                ),
                ("total_deductees", models.IntegerField(default=0)),
                (
                    "total_tds_deducted",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_tds_deposited",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FILED", "Filed"),
                            ("CORRECTED", "Corrected Return Filed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "return_file",
                    models.FileField(
                        blank=True, null=True, upload_to="form_24q/%Y/%m/"
                    ),
                ),
                (
                    "challan_file",
                    models.FileField(
                        blank=True, null=True, upload_to="challan_281/%Y/%m/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Form 24Q Return",
                "verbose_name_plural": "Form 24Q Returns",
                "ordering": ["-financial_year", "quarter"],
                "unique_together": {("financial_year", "quarter")},
            },
        ),
        migrations.CreateModel(
            name="InternationalWorker",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("passport_number", models.CharField(max_length=50)),
                ("country_of_origin", models.CharField(max_length=100)),
                ("visa_type", models.CharField(blank=True, max_length=100, null=True)),
                ("visa_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "employee_pf_pct",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
                ),
                (
                    "employer_pf_pct",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
                ),
                (
                    "has_ssa",
                    models.BooleanField(
                        default=False, help_text="Country has Social Security Agreement"
                    ),
                ),
                (
                    "ssa_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="international_worker",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "International Worker",
                "verbose_name_plural": "International Workers",
            },
        ),
        migrations.CreateModel(
            name="PFStatement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("FORM_2", "Form 2 - PF Nomination"),
                            ("FORM_10C", "Form 10C - EPS Withdrawal"),
                            ("FORM_10D", "Form 10D - Pension Claim"),
                            ("FORM_19", "Form 19 - PF Final Withdrawal"),
                            ("FORM_31", "Form 31 - PF Advance"),
                            ("FORM_13", "Form 13 - Transfer Claim"),
                            ("FORM_11", "Form 11 - New Employee Declaration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("form_date", models.DateField()),
                (
                    "form_file",
                    models.FileField(
                        blank=True, null=True, upload_to="pf_forms/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "epfo_reference",
                    models.CharField(
                        blank=True,
                        help_text="EPFO acknowledgment/claim ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pf_statements",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "PF Statement",
                "verbose_name_plural": "PF Statements",
                "ordering": ["-form_date", "employee"],
            },
        ),
        migrations.CreateModel(
            name="LowerDeductionCertificate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("FORM_15G", "Form 15G - Lower TDS (Below 60 years)"),
                            ("FORM_15H", "Form 15H - No TDS (Senior Citizen 60+)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "estimated_tax_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("reason_for_no_tax", models.TextField(blank=True, null=True)),
                ("submitted_date", models.DateField()),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="form_15gh/%Y/%m/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lower_deduction_certs",
                        to="hr.employee",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lower Deduction Certificate",
                "verbose_name_plural": "Lower Deduction Certificates (15G/15H)",
                "unique_together": {("employee", "financial_year", "certificate_type")},
            },
        ),
        migrations.CreateModel(
            name="PTEnrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                (
                    "enrollment_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="pt_enrollments/%Y/%m/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pt_enrollments",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "PT Enrollment",
                "verbose_name_plural": "PT Enrollments",
                "unique_together": {("employee", "state")},
            },
        ),
        migrations.CreateModel(
            name="VPFContribution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "vpf_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Additional PF contribution % above statutory 12%",
                        max_digits=5,
                    ),
                ),
                (
                    "vpf_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpf_contributions",
                        to="hr.employee",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpf_contributions",
                        to="hr.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPF Contribution",
                "verbose_name_plural": "VPF Contributions",
                "ordering": ["-year", "-month"],
                "unique_together": {("employee", "month", "year")},
            },
        ),
    ]
