# Generated by Django 5.2.12 on 2026-07-13 08:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_remove_user_department_user_departments"),
        ("hr", "0008_esicard_form12ba_form24qreturn_internationalworker_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeReferral",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("referred_name", models.CharField(max_length=200)),
                ("referred_email", models.EmailField(max_length=254)),
                (
                    "referred_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "referred_resume",
                    models.FileField(
                        blank=True, null=True, upload_to="referral_resumes/%Y/%m/"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship with referred person (ex-colleague, friend, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REFERRED", "Referred"),
                            ("CONTACTED", "Contacted"),
                            ("INTERVIEWED", "Interviewed"),
                            ("HIRED", "Hired - Bonus Due"),
                            ("BONUS_PAID", "Bonus Paid"),
                            ("REJECTED", "Rejected"),
                            ("JOINED", "Joined - Bonus Pending"),
                        ],
                        default="REFERRED",
                        max_length=20,
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Referral bonus amount (if applicable)",
                        max_digits=15,
                    ),
                ),
                ("bonus_paid", models.BooleanField(default=False)),
                ("bonus_paid_date", models.DateField(blank=True, null=True)),
                ("referral_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "referred_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="hr.candidate",
                    ),
                ),
                (
                    "referring_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="hr.employee",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="hr.jobrequisition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Referral",
                "verbose_name_plural": "Employee Referrals",
                "ordering": ["-referral_date"],
            },
        ),
        migrations.CreateModel(
            name="InternalJobPosting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job title as shown to employees", max_length=200
                    ),
                ),
                ("description", models.TextField(help_text="Detailed job description")),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="Required qualifications and skills",
                        null=True,
                    ),
                ),
                ("responsibilities", models.TextField(blank=True, null=True)),
                ("vacancies", models.PositiveIntegerField(default=1)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("CONTRACT", "Contract"),
                            ("TRAINEE", "Trainee"),
                            ("INTERN", "Intern"),
                            ("PART_TIME", "Part-Time"),
                        ],
                        default="PERMANENT",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Target grade/band",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("posting_date", models.DateField(auto_now_add=True)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("expected_joining_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open for Applications"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("total_applications", models.IntegerField(default=0, editable=False)),
                ("shortlisted_count", models.IntegerField(default=0, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.designation",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked job requisition (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_postings",
                        to="hr.jobrequisition",
                    ),
                ),
                (
                    "work_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.worklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Job Posting (IJP)",
                "verbose_name_plural": "Internal Job Postings (IJP)",
                "ordering": ["-posting_date"],
            },
        ),
        migrations.CreateModel(
            name="PreJoiningDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "portal_token",
                    models.CharField(
                        blank=True,
                        help_text="Unique token for candidate portal access",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "portal_expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Portal access expiry date (typically 30 days before joining)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Upload"),
                            ("UPLOADED", "Uploaded"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected - Re-upload Required"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last activity timestamp in portal",
                        null=True,
                    ),
                ),
                (
                    "documents_uploaded",
                    models.IntegerField(
                        default=0, help_text="Number of documents uploaded"
                    ),
                ),
                (
                    "total_documents_required",
                    models.IntegerField(
                        default=13, help_text="Total number of documents required"
                    ),
                ),
                ("welcome_email_sent", models.BooleanField(default=False)),
                ("welcome_email_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_joining_docs",
                        to="hr.candidate",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_joining_documents",
                        to="hr.offerletter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Joining Document Portal",
                "verbose_name_plural": "Pre-Joining Document Portals",
            },
        ),
        migrations.CreateModel(
            name="InternalJobApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cover_note",
                    models.TextField(
                        blank=True,
                        help_text="Why the employee is interested",
                        null=True,
                    ),
                ),
                (
                    "current_designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "current_department",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "relevant_experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "manager_endorsed",
                    models.BooleanField(
                        blank=True,
                        help_text="Current manager's endorsement (None=Pending, True=Endorsed, False=Not Endorsed)",
                        null=True,
                    ),
                ),
                ("manager_comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("INTERVIEWED", "Interviewed"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_applications",
                        to="hr.employee",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="hr.internaljobposting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Job Application",
                "verbose_name_plural": "Internal Job Applications",
                "ordering": ["-applied_date"],
                "unique_together": {("posting", "applicant")},
            },
        ),
        migrations.CreateModel(
            name="OnboardingBuddy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("BUDDY", "Buddy"), ("MENTOR", "Mentor")],
                        default="BUDDY",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Buddy program end date (typically 90 days)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "buddy_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rating given by new employee to buddy (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "new_employee_feedback",
                    models.TextField(
                        blank=True,
                        help_text="New employee's feedback about buddy program",
                        null=True,
                    ),
                ),
                (
                    "buddy_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Buddy's feedback about the new employee",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "buddy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_assignments",
                        to="hr.employee",
                    ),
                ),
                (
                    "new_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_buddies",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Buddy",
                "verbose_name_plural": "Onboarding Buddies",
                "unique_together": {("new_employee", "buddy", "role")},
            },
        ),
        migrations.CreateModel(
            name="OnboardingFeedback",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("DAY_30", "Day 30 Check-in"),
                            ("DAY_60", "Day 60 Check-in"),
                            ("DAY_90", "Day 90 Check-in"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "overall_satisfaction",
                    models.IntegerField(
                        help_text="How satisfied are you with your role?",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "onboarding_process",
                    models.IntegerField(
                        help_text="How would you rate the onboarding process?",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "buddy_support",
                    models.IntegerField(
                        blank=True,
                        help_text="How helpful was your buddy/mentor?",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "role_clarity",
                    models.IntegerField(
                        help_text="How clear are your role and responsibilities?",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("what_is_going_well", models.TextField(blank=True, null=True)),
                ("challenges_faced", models.TextField(blank=True, null=True)),
                ("suggestions", models.TextField(blank=True, null=True)),
                (
                    "would_recommend",
                    models.BooleanField(
                        blank=True,
                        help_text="Would you recommend this company to others?",
                        null=True,
                    ),
                ),
                ("submitted_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_feedbacks",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Feedback",
                "verbose_name_plural": "Onboarding Feedbacks",
                "unique_together": {("employee", "feedback_type")},
            },
        ),
    ]
