# Generated by Django 5.2.12 on 2026-07-13 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_remove_user_department_user_departments"),
        ("hr", "0009_employeereferral_internaljobposting_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingScale",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 5-Point Scale, 9-Point Scale", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "scale_type",
                    models.CharField(
                        choices=[
                            ("STANDARD_5", "5-Point Standard"),
                            ("STANDARD_9", "9-Point Standard"),
                            ("CUSTOM", "Custom Scale"),
                            ("YES_NO", "Yes/No"),
                            ("SATISFACTION", "Satisfaction (1-5)"),
                        ],
                        default="STANDARD_5",
                        max_length=20,
                    ),
                ),
                (
                    "min_rating",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                (
                    "max_rating",
                    models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
                ),
                (
                    "step",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.5,
                        help_text="Increment step (e.g. 0.5, 1.0)",
                        max_digits=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Rating Scale",
                "verbose_name_plural": "Rating Scales",
            },
        ),
        migrations.CreateModel(
            name="AppraisalFormTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Form template name", max_length=200),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("SELF_APPRAISAL", "Self Appraisal"),
                            ("MANAGER_APPRAISAL", "Manager Appraisal"),
                            ("PEER_REVIEW", "Peer Review"),
                            ("360_FEEDBACK", "360° Feedback"),
                            ("EXIT_INTERVIEW", "Exit Interview"),
                            ("PROBATION", "Probation Review"),
                        ],
                        default="SELF_APPRAISAL",
                        max_length=30,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Published templates can be used in appraisal cycles",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicable_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all departments",
                        to="authentication.department",
                    ),
                ),
                (
                    "applicable_designations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all designations",
                        to="hr.designation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rating_scale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default rating scale for this form",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.ratingscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appraisal Form Template",
                "verbose_name_plural": "Appraisal Form Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalFormSection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Section title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Instructions or context for this section",
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "weightage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weightage of this section in the overall form (sum of all sections = 100%)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "form_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="hr.appraisalformtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appraisal Form Section",
                "verbose_name_plural": "Appraisal Form Sections",
                "ordering": ["form_template", "order"],
            },
        ),
        migrations.CreateModel(
            name="BellCurveConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Standard Bell Curve, Aggressive, Soft",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "distribution",
                    models.JSONField(
                        default=dict,
                        help_text='{"5": 10, "4": 20, "3": 40, "2": 20, "1": 10} in percentages',
                    ),
                ),
                (
                    "is_forced_ranking",
                    models.BooleanField(
                        default=False,
                        help_text="If True, ratings are auto-adjusted to fit the curve",
                    ),
                ),
                (
                    "allow_override",
                    models.BooleanField(
                        default=True,
                        help_text="Allow managers to override forced rank with justification",
                    ),
                ),
                (
                    "min_employees_for_curve",
                    models.IntegerField(
                        default=20,
                        help_text="Minimum employees needed to apply bell curve",
                    ),
                ),
                (
                    "curve_type",
                    models.CharField(
                        choices=[
                            ("STANDARD_BELL", "Standard Bell Curve"),
                            ("SKEWED_RIGHT", "Skewed Right (More High Performers)"),
                            ("SKEWED_LEFT", "Skewed Left (More Low Performers)"),
                            ("FLAT", "Flat Distribution"),
                            ("CUSTOM", "Custom Distribution"),
                        ],
                        default="STANDARD_BELL",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bell_curve_configs",
                        to="hr.appraisalcycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bell Curve Configuration",
                "verbose_name_plural": "Bell Curve Configurations",
            },
        ),
        migrations.CreateModel(
            name="GoalCascade",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company Goal"),
                            ("DEPARTMENT", "Department Goal"),
                            ("TEAM", "Team Goal"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source_description",
                    models.TextField(help_text="The higher-level goal description"),
                ),
                (
                    "target_team",
                    models.CharField(
                        blank=True,
                        help_text="Team name (if cascading to a team)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "contribution",
                    models.TextField(
                        blank=True,
                        help_text="How does the target contribute to this source goal?",
                        null=True,
                    ),
                ),
                (
                    "weightage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="% of the source goal this cascade represents",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "aligned_goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="The PerformanceGoal this cascade is linked to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cascaded_from",
                        to="hr.performancegoal",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_cascades",
                        to="hr.appraisalcycle",
                    ),
                ),
                (
                    "target_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department this goal cascades to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.department",
                    ),
                ),
                (
                    "target_employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee this cascades to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cascaded_goals",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal Cascade",
                "verbose_name_plural": "Goal Cascades",
            },
        ),
        migrations.CreateModel(
            name="PromotionMatrix",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. FY 2025-26 Promotion Matrix", max_length=100
                    ),
                ),
                (
                    "min_rating",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                (
                    "max_rating",
                    models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_matrices",
                        to="hr.appraisalcycle",
                    ),
                ),
                (
                    "rating_scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.ratingscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Matrix",
                "verbose_name_plural": "Promotion Matrices",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="PromotionMatrixRow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating_from",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Minimum rating for this bracket",
                        max_digits=3,
                    ),
                ),
                (
                    "rating_to",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Maximum rating for this bracket",
                        max_digits=3,
                    ),
                ),
                (
                    "min_increment_pct",
                    models.DecimalField(
                        decimal_places=2, help_text="Minimum increment %", max_digits=5
                    ),
                ),
                (
                    "max_increment_pct",
                    models.DecimalField(
                        decimal_places=2, help_text="Maximum increment %", max_digits=5
                    ),
                ),
                (
                    "promotion_recommended",
                    models.BooleanField(
                        default=False,
                        help_text="Is promotion recommended for this rating bracket?",
                    ),
                ),
                (
                    "promotion_notes",
                    models.TextField(
                        blank=True,
                        help_text="E.g. 'Fast track promotion eligible'",
                        null=True,
                    ),
                ),
                (
                    "bonus_recommended",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Recommended performance bonus % of CTC",
                        max_digits=5,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="hr.promotionmatrix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Matrix Row",
                "verbose_name_plural": "Promotion Matrix Rows",
                "ordering": ["matrix", "rating_from"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalFormQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("RATING", "Rating (Scale)"),
                            ("TEXT", "Text/Open Ended"),
                            ("MULTI_CHOICE", "Multiple Choice"),
                            ("YES_NO", "Yes/No"),
                            ("DROPDOWN", "Dropdown"),
                            ("DATE", "Date"),
                            ("FILE_UPLOAD", "File Upload"),
                        ],
                        default="RATING",
                        max_length=30,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of options for multi-choice/dropdown questions",
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "max_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Max characters for text response",
                        null=True,
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("help_text", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="hr.appraisalformsection",
                    ),
                ),
                (
                    "rating_scale",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to use form template default scale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.ratingscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appraisal Form Question",
                "verbose_name_plural": "Appraisal Form Questions",
                "ordering": ["section", "order"],
            },
        ),
        migrations.CreateModel(
            name="AppraisalFormResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "respondent_type",
                    models.CharField(
                        choices=[
                            ("SELF", "Self"),
                            ("MANAGER", "Manager"),
                            ("PEER", "Peer"),
                            ("SUBORDINATE", "Subordinate"),
                            ("HR", "HR"),
                        ],
                        default="SELF",
                        max_length=20,
                    ),
                ),
                (
                    "rating_value",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("text_response", models.TextField(blank=True, null=True)),
                (
                    "choice_response",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "file_response",
                    models.FileField(
                        blank=True, null=True, upload_to="appraisal_responses/%Y/%m/"
                    ),
                ),
                ("date_response", models.DateField(blank=True, null=True)),
                ("submitted_date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_draft",
                    models.BooleanField(
                        default=True, help_text="If True, response is saved as draft"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hr.appraisalformquestion",
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who answered this question (employee, manager, peer)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_responses",
                        to="hr.performancereview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appraisal Form Response",
                "verbose_name_plural": "Appraisal Form Responses",
                "unique_together": {("review", "question", "respondent_type")},
            },
        ),
        migrations.CreateModel(
            name="AppraisalCycleStage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("GOAL_SETTING", "Goal Setting"),
                            ("MID_YEAR_REVIEW", "Mid-Year Review"),
                            ("SELF_APPRAISAL", "Self Appraisal"),
                            ("MANAGER_APPRAISAL", "Manager Appraisal"),
                            ("PEER_FEEDBACK", "Peer Feedback"),
                            ("CALIBRATION", "Calibration"),
                            ("RATING_FINALISATION", "Rating Finalisation"),
                            ("APPRAISAL_DISCUSSION", "Appraisal Discussion"),
                            ("INCREMENT_PROMOTION", "Increment & Promotion Decision"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this stage", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="hr.appraisalcycle",
                    ),
                ),
                (
                    "form_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cycle_stages",
                        to="hr.appraisalformtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appraisal Cycle Stage",
                "verbose_name_plural": "Appraisal Cycle Stages",
                "ordering": ["cycle", "order"],
                "unique_together": {("cycle", "stage_type")},
            },
        ),
        migrations.CreateModel(
            name="GoalLibrary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Goal title", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed goal description"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Financial"),
                            ("CUSTOMER", "Customer"),
                            ("INTERNAL", "Internal Process"),
                            ("LEARNING", "Learning & Growth"),
                            ("PROJECT", "Project Delivery"),
                            ("COMPLIANCE", "Compliance & Risk"),
                            ("INNOVATION", "Innovation"),
                            ("LEADERSHIP", "Leadership"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("SMART", "SMART Goal"),
                            ("OKR", "Objective & Key Result"),
                            ("KPI", "KPI Target"),
                            ("PROJECT", "Project Milestone"),
                        ],
                        default="SMART",
                        max_length=20,
                    ),
                ),
                (
                    "success_metric",
                    models.TextField(
                        blank=True, help_text="How will success be measured?", null=True
                    ),
                ),
                (
                    "target_value",
                    models.CharField(
                        blank=True,
                        help_text="Expected target value/outcome",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "suggested_weightage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Suggested weightage percentage",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department this goal template applies to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Designation/role this goal template applies to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.designation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal Library Template",
                "verbose_name_plural": "Goal Library Templates",
                "ordering": ["category", "title"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="hr_goallibr_categor_fa8544_idx"
                    ),
                    models.Index(
                        fields=["department", "designation"],
                        name="hr_goallibr_departm_ae0945_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RatingScaleOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating_value",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="The numeric rating value",
                        max_digits=3,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short label like 'Outstanding', 'Meets Expectations'",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this rating means",
                        null=True,
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for visual representation (e.g. #22C55E)",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="hr.ratingscale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating Scale Option",
                "verbose_name_plural": "Rating Scale Options",
                "ordering": ["scale", "-rating_value"],
                "unique_together": {("scale", "rating_value")},
            },
        ),
    ]
