# Generated by Django 5.2.12 on 2026-07-13 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0010_ratingscale_appraisalformtemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAccessRestriction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Rule name e.g. Payroll IP Whitelist", max_length=100
                    ),
                ),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("WHITELIST", "Whitelist - Only allow listed IPs"),
                            ("BLACKLIST", "Blacklist - Block listed IPs"),
                        ],
                        default="WHITELIST",
                        max_length=20,
                    ),
                ),
                (
                    "allowed_networks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of CIDR ranges e.g. ["10.0.0.0/8", "192.168.1.0/24"]',
                    ),
                ),
                (
                    "blocked_networks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of CIDR ranges to block",
                    ),
                ),
                (
                    "role_required",
                    models.CharField(
                        blank=True,
                        help_text="Role this restriction applies to (ANY for all)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "applicable_modules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of modules: ["payroll", "employee_data", "compliance"]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user this restriction applies to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Access Restriction",
                "verbose_name_plural": "IP Access Restrictions",
                "ordering": ["name"],
            },
        ),
    ]
