# Generated by Django 5.2.12 on 2026-07-14 02:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0011_ipaccessrestriction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POSHComplaint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("VERBAL", "Verbal Harassment"),
                            ("PHYSICAL", "Physical Harassment"),
                            ("VISUAL", "Visual / Display"),
                            ("CYBER", "Cyber / Electronic"),
                            ("THIRD_PARTY", "Third Party Harassment"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("incident_date", models.DateField()),
                (
                    "incident_location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("description", models.TextField()),
                (
                    "supporting_evidence",
                    models.FileField(
                        blank=True, null=True, upload_to="posh_evidence/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_INVESTIGATION", "Under Investigation"),
                            ("INQUIRY_COMPLETED", "Inquiry Completed"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("inquiry_start_date", models.DateField(blank=True, null=True)),
                ("inquiry_completed_date", models.DateField(blank=True, null=True)),
                ("resolution_date", models.DateField(blank=True, null=True)),
                ("inquiry_findings", models.TextField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True, null=True)),
                ("closure_notes", models.TextField(blank=True, null=True)),
                ("is_confidential", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "complainant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posh_complaints_filed",
                        to="hr.employee",
                    ),
                ),
                (
                    "icc_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posh_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "presiding_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posh_presiding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posh_complaints_against",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "POSH Complaint",
                "verbose_name_plural": "POSH Complaints",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_posh_case", "Can view POSH case details"),
                    ("can_manage_icc", "Can manage ICC committee"),
                ],
            },
        ),
        migrations.CreateModel(
            name="POSHInquiryNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("is_confidential", models.BooleanField(default=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="posh_inquiry_notes/%Y/%m/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry_notes",
                        to="hr.poshcomplaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "POSH Inquiry Note",
                "verbose_name_plural": "POSH Inquiry Notes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalaryFreeze",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "freeze_reason",
                    models.CharField(
                        choices=[
                            ("NOTICE_PERIOD", "Under Notice Period"),
                            ("DISCIPLINARY", "Disciplinary Proceedings"),
                            ("DISPUTE", "Salary Dispute"),
                            ("LEGAL", "Legal Proceedings"),
                            ("ABSENCE", "Extended Unauthorized Absence"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(help_text="Reason for salary freeze")),
                ("frozen_date", models.DateTimeField(auto_now_add=True)),
                ("unfrozen_date", models.DateTimeField(blank=True, null=True)),
                ("unfrozen_reason", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_freezes",
                        to="hr.employee",
                    ),
                ),
                (
                    "frozen_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_freezes_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unfrozen_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_freezes_released",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Freeze",
                "verbose_name_plural": "Salary Freezes",
                "ordering": ["-frozen_date"],
            },
        ),
        migrations.CreateModel(
            name="StayInterview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("interview_date", models.DateField()),
                (
                    "what_keeps_you",
                    models.TextField(help_text="What keeps you at the company?"),
                ),
                (
                    "what_would_change",
                    models.TextField(help_text="What would make you leave?"),
                ),
                ("career_aspirations", models.TextField(blank=True, null=True)),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "engagement_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("identified_concerns", models.TextField(blank=True, null=True)),
                ("action_items", models.TextField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FOLLOW_UP", "Follow-up Required"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "retention_risk",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical - Immediate Attention"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_stay_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stay_interviews",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stay Interview",
                "verbose_name_plural": "Stay Interviews",
                "ordering": ["-interview_date"],
            },
        ),
        migrations.CreateModel(
            name="DataConsentRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("DATA_COLLECTION", "Data Collection Consent"),
                            ("DATA_PROCESSING", "Data Processing Consent"),
                            ("DATA_RETENTION", "Data Retention Consent"),
                            ("DATA_SHARING", "Data Sharing Consent"),
                            (
                                "BACKGROUND_VERIFICATION",
                                "Background Verification Consent",
                            ),
                            ("BANK_DETAILS", "Bank Details Processing"),
                            ("EMERGENCY_CONTACT", "Emergency Contact Processing"),
                            ("HEALTH_DATA", "Health Data Processing"),
                            ("GENERAL", "General Consent"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GRANTED", "Granted"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("consent_version", models.CharField(max_length=20)),
                (
                    "consent_text",
                    models.TextField(help_text="Full text of what was consented to"),
                ),
                ("consent_date", models.DateTimeField(auto_now_add=True)),
                ("granted_date", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_date", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "consent_method",
                    models.CharField(
                        choices=[
                            ("PORTAL", "ESS Portal"),
                            ("EMAIL", "Email"),
                            ("SIGNED_FORM", "Signed Form"),
                            ("HR_INTERVIEW", "HR Interview"),
                            ("API", "API Integration"),
                        ],
                        default="PORTAL",
                        max_length=30,
                    ),
                ),
                (
                    "consent_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="consent_proofs/%Y/%m/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_consents",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Consent Record",
                "verbose_name_plural": "Data Consent Records",
                "ordering": ["-consent_date"],
                "unique_together": {("employee", "consent_type", "consent_version")},
            },
        ),
    ]
