# Generated by Django 6.0.7 on 2026-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_poshcomplaint_poshinquirynote_salaryfreeze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_file',
            field=models.FileField(max_length=255, upload_to='hr/employee_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='employeedocumentversion',
            name='document_file',
            field=models.FileField(max_length=255, upload_to='hr/employee_documents_versions/%Y/%m/'),
        ),
    ]
