# Generated by Django 6.0.7 on 2026-07-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_increase_document_file_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20),
        ),
    ]
