# Generated by Django 6.0.7 on 2026-07-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_add_resignation_status_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('candidate', 'requisition')},
        ),
    ]
