# Generated by Django 5.2.12 on 2026-07-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_alter_calendartodo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartodo',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
