# Generated by Django 5.2.12 on 2026-07-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0004_calendartodo_hold_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartodo',
            name='extension_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
