# Generated by Django 5.2.12 on 2026-07-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0005_calendartodo_extension_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartodo',
            name='completion_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
