# Generated by Django 5.2.12 on 2026-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0006_calendartodo_completion_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartodo',
            name='followup_cancellation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
