# Generated by Django 5.2.12 on 2026-07-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0007_calendartodo_followup_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartodo',
            name='followup_failed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
