# Generated by Django 5.2.12 on 2026-07-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_pipeline_pipeline_type_and_more'),
        ('event_calendar', '0008_calendartodo_followup_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartodo',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='crm.pipeline'),
        ),
    ]
