# Generated by Django 6.0.6 on 2026-08-01 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_crm_options'),
        ('event_calendar', '0009_calendartodo_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartodo',
            name='crm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='crm.crm'),
        ),
    ]
