# Generated by Django 6.0.6 on 2026-06-21 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_created_by_inventoryitem_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('conversion_factor', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
            options={
                'verbose_name': 'Unit Conversion',
                'verbose_name_plural': 'Unit Conversions',
                'ordering': ['from_unit', 'to_unit'],
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ['category_name'], 'verbose_name': 'Item Category', 'verbose_name_plural': 'Item Categories'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_name'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_code',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='brand',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='category_code',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='category_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='symbol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('tenant_id', 'brand_code')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('tenant_id', 'category_code')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('tenant_id', 'unit_code')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant_id', 'brand_code'], name='inventory_b_tenant__921b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant_id', 'brand_name'], name='inventory_b_tenant__804369_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_b_tenant__e5321d_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['tenant_id', 'category_code'], name='inventory_i_tenant__7eaac5_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['tenant_id', 'category_name'], name='inventory_i_tenant__98caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['tenant_id', 'parent'], name='inventory_i_tenant__38cb90_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcategory',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__6fd9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant_id', 'unit_code'], name='inventory_u_tenant__adaf54_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant_id', 'unit_name'], name='inventory_u_tenant__19684a_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant_id', 'status'], name='inventory_u_tenant__412d6d_idx'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='inventory.unit'),
        ),
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.AddIndex(
            model_name='unitconversion',
            index=models.Index(fields=['tenant_id', 'from_unit'], name='inventory_u_tenant__31c46c_idx'),
        ),
        migrations.AddIndex(
            model_name='unitconversion',
            index=models.Index(fields=['tenant_id', 'to_unit'], name='inventory_u_tenant__1a247b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together={('tenant_id', 'from_unit', 'to_unit')},
        ),
    ]
