# Generated by Django 6.0.6 on 2026-06-21 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_upgrade_category_unit_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('type_code', models.CharField(db_index=True, max_length=50)),
                ('type_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
                'ordering': ['type_name'],
                'indexes': [models.Index(fields=['tenant_id', 'type_code'], name='inventory_i_tenant__3757d7_idx'), models.Index(fields=['tenant_id', 'type_name'], name='inventory_i_tenant__cde761_idx'), models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__4df862_idx')],
                'unique_together': {('tenant_id', 'type_code')},
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('location_code', models.CharField(db_index=True, max_length=100)),
                ('location_name', models.CharField(max_length=500)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('max_capacity', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum storage capacity', max_digits=20, null=True)),
                ('capacity_unit', models.CharField(blank=True, help_text='e.g. PCS, KG, Seats', max_length=50)),
                ('allow_reservations', models.BooleanField(default=True)),
                ('allow_transfers', models.BooleanField(default=True)),
                ('allow_sales', models.BooleanField(default=True)),
                ('allow_purchases', models.BooleanField(default=True)),
                ('allow_audits', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to=settings.AUTH_USER_MODEL)),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='inventory.inventorylocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_locations', to=settings.AUTH_USER_MODEL)),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventory.inventorylocationtype')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['location_name'],
                'indexes': [models.Index(fields=['tenant_id', 'location_code'], name='inventory_i_tenant__154a6a_idx'), models.Index(fields=['tenant_id', 'location_name'], name='inventory_i_tenant__d5bb90_idx'), models.Index(fields=['tenant_id', 'location_type'], name='inventory_i_tenant__db74d0_idx'), models.Index(fields=['tenant_id', 'parent_location'], name='inventory_i_tenant__6f0e18_idx'), models.Index(fields=['tenant_id', 'status'], name='inventory_i_tenant__1379cc_idx'), models.Index(fields=['tenant_id', 'city'], name='inventory_i_tenant__f82ae9_idx')],
                'unique_together': {('tenant_id', 'location_code')},
            },
        ),
    ]
