# Generated by Django 6.0.6 on 2026-06-21 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_location_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Unit cost price for valuation', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_stock_level',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Maximum desired stock level', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_stock_level',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Minimum stock before low-stock alert', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stock level at which to reorder', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Unit selling price', max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('transaction_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('LOST', 'Lost'), ('EXPIRED', 'Expired'), ('CONSUMPTION', 'Consumption'), ('ADJUSTMENT', 'Adjustment'), ('RESERVATION', 'Reservation'), ('RESERVATION_RELEASE', 'Reservation Release')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Positive = in, Negative = out', max_digits=20)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='e.g. PURCHASE_ORDER, SALES_ORDER, TRANSFER', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='ID of the source document', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='inventory.inventoryitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='inventory.inventorylocation')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'item', 'location'], name='inventory_s_tenant__89d040_idx'), models.Index(fields=['tenant_id', 'item'], name='inventory_s_tenant__d755b1_idx'), models.Index(fields=['tenant_id', 'location'], name='inventory_s_tenant__834e25_idx'), models.Index(fields=['tenant_id', 'transaction_type'], name='inventory_s_tenant__05a291_idx'), models.Index(fields=['tenant_id', 'created_at'], name='inventory_s_tenant__14e4f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('physical_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('in_transit_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('damaged_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_summaries', to='inventory.inventoryitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_summaries', to='inventory.inventorylocation')),
            ],
            options={
                'verbose_name': 'Stock Summary',
                'verbose_name_plural': 'Stock Summaries',
                'indexes': [models.Index(fields=['tenant_id', 'item'], name='inventory_s_tenant__fae2d3_idx'), models.Index(fields=['tenant_id', 'location'], name='inventory_s_tenant__986b2f_idx'), models.Index(fields=['tenant_id', 'physical_quantity'], name='inventory_s_tenant__f2a34c_idx')],
                'unique_together': {('tenant_id', 'item', 'location')},
            },
        ),
    ]
