# Generated by Django 5.2.12 on 2026-04-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_auditlog_emailverificationtoken_loginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="emailverificationtoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
