# Generated by Django 5.2.12 on 2026-04-11 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_auditlog_updated_at_and_more"),
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization/Company this user belongs to. Superadmins can be global (NULL)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="menus.organization",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Superadmin", "Superadmin"),
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Staff", "Staff"),
                    ("Vendor", "Vendor"),
                    ("User", "User"),
                    ("Others", "Others"),
                ],
                default="User",
                help_text="ID generation depends on the role. Once you submit it will be permanent.",
                max_length=100,
            ),
        ),
    ]
