# Generated by Django 5.2.12 on 2026-04-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_organization_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="action_target",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that was affected by this action (for user management operations)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target_changes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores what fields changed with old/new values for update operations",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("password_change", "Password Change"),
                    ("email_change", "Email Change"),
                    ("email_verify", "Email Verification"),
                    ("mobile_verify", "Mobile Verification"),
                    ("2fa_setup", "2FA Setup"),
                    ("2fa_attempt", "2FA Attempt"),
                    ("profile_update", "Profile Update"),
                    ("user_create", "User Created"),
                    ("user_update", "User Updated"),
                    ("user_delete", "User Deleted"),
                    ("user_activate", "User Activated"),
                    ("user_role_change", "User Role Changed"),
                    ("user_department_change", "User Department Changed"),
                    ("user_supervisor_change", "Supervisor Assignment Changed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_target", "created_at"],
                name="authenticat_action__a8d5c1_idx",
            ),
        ),
    ]
