# Generated by Django 5.2.12 on 2026-04-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auditlog_action_target_auditlog_target_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('email_change', 'Email Change'), ('email_verify', 'Email Verification'), ('mobile_verify', 'Mobile Verification'), ('2fa_setup', '2FA Setup'), ('2fa_attempt', '2FA Attempt'), ('profile_update', 'Profile Update'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_activate', 'User Activated'), ('user_role_change', 'User Role Changed'), ('user_department_change', 'User Department Changed'), ('user_supervisor_change', 'Supervisor Assignment Changed'), ('invoice_create', 'Invoice Created'), ('invoice_update', 'Invoice Updated'), ('invoice_delete', 'Invoice Deleted'), ('invoice_submit', 'Invoice Submitted'), ('invoice_approve', 'Invoice Approved'), ('invoice_reject', 'Invoice Rejected'), ('invoice_download', 'Invoice Downloaded')], max_length=50),
        ),
    ]
