# Generated by Django 6.0.7 on 2026-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_department_user_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Superadmin', 'Superadmin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff'), ('Vendor', 'Vendor'), ('Finance', 'Finance'), ('Payroll Executive', 'Payroll Executive'), ('User', 'User'), ('Others', 'Others')], default='User', help_text='ID generation depends on the role. Once you submit it will be permanent.', max_length=100),
        ),
    ]
