# Generated by Django 5.2.12 on 2026-04-26 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_importbatch_contact_source_contact_import_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='lead', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Estimated deal value', max_digits=12)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('probability', models.IntegerField(default=0, help_text='Close probability percentage')),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(help_text='The contact associated with this CRM entry', on_delete=django.db.models.deletion.CASCADE, related_name='crm_pipelines', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'CRM Entry',
                'verbose_name_plural': 'CRM Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
