# Generated by Django 5.2.12 on 2026-04-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crm',
            name='expected_close_date',
        ),
        migrations.RemoveField(
            model_name='crm',
            name='probability',
        ),
    ]
