# Generated by Django 5.2.12 on 2026-04-28 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_crm_expected_close_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='crm',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='The pipeline this deal belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.pipeline'),
        ),
    ]
