# Generated by Django 5.2.12 on 2026-05-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_import_batch'),
        ('crm', '0003_pipeline_crm_pipeline'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crm',
            index=models.Index(fields=['pipeline', 'stage'], name='crm_crm_pipelin_d94bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='crm',
            index=models.Index(fields=['created_at'], name='crm_crm_created_e6e10a_idx'),
        ),
    ]
