# Generated by Django 5.2.12 on 2026-05-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_crm_crm_crm_pipelin_d94bb0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['name'], name='crm_pipelin_name_0a8b7c_idx'),
        ),
    ]
