# Generated by Django 5.2.12 on 2026-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_department_user_departments'),
        ('crm', '0007_noop_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='pipelines', to='authentication.department'),
        ),
    ]
