# Generated by Django 5.2.12 on 2026-05-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_crm_crm_pipelin_d94bb0_idx_crm_crm_pipelin_d051ad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='assignment_type',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('least_loaded', 'Least Loaded'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
