# Generated by Django 5.2.12 on 2026-05-14 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_import_batch'),
        ('crm', '0010_rename_crm_crm_pipelin_d94bb0_idx_crm_crm_pipelin_d051ad_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='crm',
            index=models.Index(fields=['pipeline', 'assigned_user'], name='crm_crm_pipeline_user_idx'),
        ),
    ]
