# Generated by Django 5.2.12 on 2026-05-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_rename_crm_crm_pipelin_d94bb0_idx_crm_crm_pipelin_d051ad_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pipeline',
            name='crm_pipelin_name_0a8b7c_idx',
        ),
        # migrations.RenameIndex(
        #     model_name='crm',
        #     new_name='crm_crm_pipelin_d051ad_idx',
        #     old_name='crm_crm_pipelin_d94bb0_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='crm',
        #     new_name='crm_crm_pipelin_fb4d5e_idx',
        #     old_name='crm_crm_pipeline_user_idx',
        # ),
    ]
