# Generated by Django 5.2.12 on 2026-05-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_remove_pipeline_crm_pipelin_name_0a8b7c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='mandatory_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
