# Generated by Django 5.2.12 on 2026-05-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_rename_crm_crm_pipelin_d94bb0_idx_crm_crm_pipelin_d051ad_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='custom_fields_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
