# Generated by Django 5.2.12 on 2026-05-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_rename_crm_crm_pipelin_d94bb0_idx_crm_crm_pipelin_d051ad_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='crm',
                    new_name='crm_crm_pipelin_stage_idx',
                    old_name='crm_crm_pipelin_d94bb0_idx',
                ),
                migrations.RenameIndex(
                    model_name='crm',
                    new_name='crm_crm_created_at_idx',
                    old_name='crm_crm_created_e6e10a_idx',
                ),
                migrations.RenameIndex(
                    model_name='crm',
                    new_name='crm_crm_pipelin_user_idx',
                    old_name='crm_crm_pipeline_user_idx',
                ),
            ]
        )
    ]
