# Generated by Django 5.2.12 on 2026-05-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_rename_crm_crm_pipelin_d94bb0_idx_crm_crm_pipelin_stage_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='custom_fields_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
