# Generated by Django 5.2.12 on 2026-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_pipeline_custom_fields_enabled'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['pipeline', 'order'], name='crm_stage_pipeline_order_idx'),
        ),
    ]
