# Generated by Django 5.2.12 on 2026-07-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_stage_crm_stage_pipeline_order_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('retarget', 'Retarget'), ('clients', 'Clients')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='assignment_type',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('least_loaded', 'Least Loaded'), ('single_user', 'Single User'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
