# Generated by Django 6.0.6 on 2026-07-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_pipeline_pipeline_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crm',
            options={'ordering': ['-updated_at'], 'verbose_name': 'CRM Entry', 'verbose_name_plural': 'CRM Entries'},
        ),
    ]
