# Generated by Django 5.2.12 on 2026-04-11 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code: 'crm', 'hr', 'inventory', etc",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name: 'Customer Relations', 'Human Resources'",
                        max_length=256,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("SYSTEM", "System Menu"), ("CUSTOM", "Custom Menu")],
                        default="SYSTEM",
                        help_text="SYSTEM: Global menus managed by Superadmin. CUSTOM: Organization-specific menus",
                        max_length=10,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier: 'dashboard', 'crm', 'custom_reports'",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name: 'Dashboard', 'Customer Relations'",
                        max_length=256,
                    ),
                ),
                (
                    "href",
                    models.CharField(
                        help_text="URL path: '/dashboard', '/crm'", max_length=256
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon name: 'LayoutDashboard', 'Users', 'Settings', etc",
                        max_length=100,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Menu section grouping: 'Operations', 'Settings', etc",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Sort order within section (0=first)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization for custom menus. NULL for system-wide menus",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_menus",
                        to="menus.organization",
                    ),
                ),
                (
                    "required_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Menu only visible if organization has purchased this product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gated_menus",
                        to="menus.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "ordering": ["section", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        help_text="User role: 'Superadmin', 'Admin', 'Manager', 'Staff', 'Vendor', 'User'",
                        max_length=50,
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="menus.menu",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization context. NULL for system-wide role assignments",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menus.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Role",
                "verbose_name_plural": "Menu Roles",
                "indexes": [
                    models.Index(
                        fields=["menu", "role"], name="menus_menur_menu_id_84777a_idx"
                    ),
                    models.Index(
                        fields=["organization", "role"],
                        name="menus_menur_organiz_8a12fb_idx",
                    ),
                ],
                "unique_together": {("menu", "role", "organization")},
            },
        ),
        migrations.CreateModel(
            name="OrgProductPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_purchases",
                        to="menus.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_purchases",
                        to="menus.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Product Purchase",
                "verbose_name_plural": "Organization Product Purchases",
                "ordering": ["-purchased_at"],
                "unique_together": {("organization", "product")},
            },
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["organization", "is_active"],
                name="menus_menu_organiz_a10bf9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["type", "is_active"], name="menus_menu_type_cca946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["section", "order"], name="menus_menu_section_1b52cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menu",
            unique_together={("organization", "code")},
        ),
    ]
