# Generated by Django 5.2.12 on 2026-05-19 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0003_menuuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="menuuser",
            name="unique_menu_user",
        ),
        migrations.RenameIndex(
            model_name="menuuser",
            new_name="menus_menuu_menu_id_d17599_idx",
            old_name="menus_menuu_menu_id_user_idx",
        ),
        migrations.RenameIndex(
            model_name="menuuser",
            new_name="menus_menuu_user_id_940fe2_idx",
            old_name="menus_menuu_user_id_menu_idx",
        ),
        migrations.AlterUniqueTogether(
            name="menuuser",
            unique_together={("menu", "user")},
        ),
    ]
