# Generated by Django 6.0.6 on 2026-07-11 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_remove_menuuser_unique_menu_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='unique_system_menu_code'),
        ),
    ]
