# Generated by Django 5.2.12 on 2026-05-29 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacollection',
            options={'ordering': ['-is_pinned', 'name'], 'verbose_name': 'Media Collection', 'verbose_name_plural': 'Media Collections'},
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned collections appear first in the list'),
        ),
        migrations.AddIndex(
            model_name='mediacollection',
            index=models.Index(fields=['is_pinned'], name='media_media_is_pinn_9b12d9_idx'),
        ),
    ]
