# Generated by Django 5.2.12 on 2026-06-08 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_mediacollection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mediacollection',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_collection_name_per_user'),
        ),
    ]
