# Generated by Django 5.2.12 on 2026-06-08 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_add_unique_collection_name_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the item was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for undo support'),
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the item was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for undo support'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['is_deleted'], name='media_media_is_dele_6d4aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacollection',
            index=models.Index(fields=['is_deleted'], name='media_media_is_dele_07bba7_idx'),
        ),
    ]
