# Generated by Django 6.0.6 on 2026-07-03 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_department_user_departments'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0004_add_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCollectionGroupPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Collection Group Permission',
                'verbose_name_plural': 'Media Collection Group Permissions',
                'ordering': ['collection', 'department'],
            },
        ),
        migrations.CreateModel(
            name='MediaCreatorGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Creator Group',
                'verbose_name_plural': 'Media Creator Groups',
                'ordering': ['department__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='mediacollection',
            name='unique_collection_name_per_user',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the source entity (Contact, Employee, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_display',
            field=models.CharField(blank=True, help_text="Human-readable label like 'Contact: John Doe (CUS-001)'", max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_object_id',
            field=models.CharField(blank=True, help_text='Primary key of the source entity', max_length=255),
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='entity_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('contact', 'Contact'), ('staff', 'Staff')], default='generic', help_text="Type of entity this collection's assets map to (Generic, Contact, or Staff)", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='mediacollection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'created_by'), name='unique_collection_name_per_user'),
        ),
        migrations.AddField(
            model_name='mediacollectiongrouppermission',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='media.mediacollection'),
        ),
        migrations.AddField(
            model_name='mediacollectiongrouppermission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_collection_permissions', to='authentication.department'),
        ),
        migrations.AddField(
            model_name='mediacreatorgroup',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_creator_permissions', to='authentication.department'),
        ),
        migrations.AddIndex(
            model_name='mediacollectiongrouppermission',
            index=models.Index(fields=['collection'], name='media_media_collect_e369e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacollectiongrouppermission',
            index=models.Index(fields=['department'], name='media_media_departm_6bc3d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediacollectiongrouppermission',
            unique_together={('collection', 'department')},
        ),
    ]
